name: Machine Learning System CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  CSV_URL: "MLproject/loan_default_preprocessing.csv"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Ambil kode repository ke dalam environment GitHub Actions
      - uses: actions/checkout@v3

      # Setup Python 3.12.7
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # Cek Env Variables
      - name: Check Env
        run: |
          echo $CSV_URL

      # Install mlflow
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      # - name: Set MLflow Tracking URI
      #   run: echo "MLFLOW_TRACKING_URI=sqlite:///mlflow.db" >> $GITHUB_ENV

      - name: Install Python dependencies
        run: |
          pip install pandas scikit-learn joblib

      # Run sebagai proyek mlflow
      - name: Run mlflow project
        run: |
          cd Workflow-CI/MLproject
          mlflow run . --env-manager=local

      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -t Workflow-CI/MLproject/mlruns/0/ | head -1)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

      # Upload file artifak ke Github Repository menggunakan Git LFS
      - name: Upload to Git LFS
        run: |
          git config --global user.name ${{ secrets.username }}
          git config --global user.email ${{ secrets.email }}
          git lfs install
          git lfs track "Workflow-CI/MLproject/mlruns/**"
          git add .gitattributes
          git commit -m "Track large files in mlruns with Git LFS" || true
          git push origin master

      # Simpan model ke GitHub Repository
      - name: Save mlruns to repo
        run: |
          git config --global user.name ${{ secrets.username }}
          git config --global user.email ${{ secrets.email }}
          git add -f Workflow-CI/MLproject/mlruns/
          git commit -m "Save mlruns and mlflow.db from CI run" || true
          git push origin master

      # git add -f Workflow-CI/MLproject/mlflow.db

      - name: Build Docker Model
        run: |
          mlflow models build-docker -m "runs:/${{ env.RUN_ID }}/model_loan_default" -n "loan-default-model"

      # jangan lupa set di setting
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker Image
        run: |
          docker tag loan-default-model ${{ secrets.DOCKER_USERNAME }}/loan-default-model:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/loan-default-model:latest
